name: deploy

on:
  push:
    branches:
      - 'agrospai'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        env:
          COMMIT_REF: ${{ github.sha }}
          BRANCH: 'agrospai'
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            rhizomik/marketplace:${{ github.sha }}
            rhizomik/marketplace:latest
